### ISSUE TITLE
Languages with accented characters

### ISSUE THREAD

**Issue by gusbrs** [cgnieder/enotez#40] opened 2022-03-21 00:54 UTC
Something went off with the latest commits in master. I'm not being able to figure out what is going on, but it seems to be triggered by languages with accented characters.

Try the following document against your master branch:

```latex
\documentclass{book}

\usepackage[spanish]{babel}
\usepackage{enotez}
\setenotez{
  split=chapter,
  backref=true,
  reset,
  totoc,
}

\usepackage{lipsum}
\usepackage{hyperref}

\ExplSyntaxOn
\NewDocumentCommand \testchapter {}
  { \prg_replicate:nn { 25 } { \lipsum[1-2]\endnote{\lipsum[3]} } }
\ExplSyntaxOff

\begin{document}

\tableofcontents{}

\chapter{Chapter 1}

\testchapter

\chapter{Chapter 2}

\testchapter

\printendnotes

\end{document}
```
I get the errors (extract):

```
./enotez-tests.tex:33: Undefined control sequence.
<argument> Notas del cap\unhbox \voidb 
                                       @x \bgroup \let \unhbox \voidb @x \se...l.33 
     
./enotez-tests.tex:33: Missing number, treated as zero.
<to be read again> 
                   @
l.33 
     
./enotez-tests.tex:33: A <box> was supposed to be here.
<to be read again> 
                   \@m 
l.33 
     
./enotez-tests.tex:33: Missing $ inserted.
<inserted text> 
                $
l.33 
     
./enotez-tests.tex:33: Undefined control sequence.
<argument> ...db @x \setbox \@tempboxa \hbox {\OT 
                                                  1\i \global \mathchardef \...l.33 
     
./enotez-tests.tex:33: Missing number, treated as zero.
<to be read again> 
                   @
l.33 
```
And the resulting PDF:

![Screenshot from 2022-03-20 21-50-28](https://user-images.githubusercontent.com/19410606/159193435-2b12735b-a6e7-42e4-9495-783b07d781bd.png)

If I check out to commit https://github.com/cgnieder/enotez/commit/5aed5b2adacdea19630856db0f8c2cefa2b4feeb, the document works as expected.

**Comment by troldtog** [comment] 2022-03-21 01:59
Notes (so far) from reproducing this:
 - Seems to be a pdfLaTeX-only problem? (Tried reproducing with XeLaTex and LuaLaTeX and things were fine)
 - git bisect says the problem occurs at commit [#a0c9df827](https://github.com/cgnieder/enotez/commit/a0c9df8276c1df03d7a6b2c6df9172f6f1016920).

**Comment by cgnieder** [comment] 2022-03-21 09:12
Thanks, I know where and why this happens. I changed some `f` expansion into `e` not bearing in mind accents aren't fully expandable.

**Comment by cgnieder** [comment] 2022-03-21 09:13
Should be fixed now.

**Closed by cgnieder** 2022-03-21 09:13 UTC

**Comment by gusbrs** [comment] 2022-03-21 09:48
Thank you!
